### DISCUSSION TITLE
DTA Request

### DISCUSSION THREAD

**Discussion by marty60** [xiaoxiaoflood/firefox-scripts#234] [General Support]
Hi,

If you're using 800 x 600 screen resolution the DTA Manager box is huge with no way to make it smaller. This is due to recent changes by Mozilla.  

xiaoxiaoflood if you could direct me to the specific location I could probably do it myself. So far I've  gone through the addon such as the skin etc but can't find the specific id of the manager.

**Comment by xiaoxiaoflood** [comment]
This would require some CSS skills to change sizes or even hide elements you don't need. I can only provide you one example without further explanation.

Install StyloaiX (or use userChrome.css if you know how to) and add this style

```css
@-moz-document url("chrome://dta-platform/content/manager.xhtml") {
  .downlinks {
    min-width: auto;
    min-height: auto;
  }

  #actionsbox {
    display: none;
  }
}
```
