### ISSUE TITLE
StyloaiX have bug with reload button

### ISSUE THREAD

**Issue by krystian3w** [xiaoxiaoflood/firefox-scripts#107]
If I disable works StyloaiX (by his option `#styloaix-enabled`) and click reload CSS `#styloaix-reload-all` that script have broken button "disable" (no longer disable reloaded css).

So I wrote CSS workaround to disable bad click by mouse (keyboard can still active option and accept by space/enter to break script):

```css
      }
		  #styloaix-enabled[label="Disabled"] ~ #styloaix-reload-all {
	        pointer-events: none;
	        color: GrayText
          }
```

beetween lines: https://github.com/xiaoxiaoflood/firefox-scripts/blob/8274daf14f5182a9598d42198592de4ce88a51b8/chrome/styloaix.uc.js#L371-L372

Maybe possible add inject to contex menu new one `[label="Disabled"]` / `[disabled]` to cover keyboards too.
