### ISSUE TITLE
fasttabswitcher extension white text on white background

### ISSUE THREAD

**Issue by sibouras** [xiaoxiaoflood/firefox-scripts#159]
text is invisible when using fasttabswitcher in dark mode
![firefox-fast-tab-white](https://user-images.githubusercontent.com/64098483/178346593-5ff85642-120b-46f5-872b-04be5db45d97.png)

**Comment by Sneakpeakcss** [comment]
In the meantime you could try changing it to your liking with css:

```css
/*searchbar colors*/
#tabswitcher-window #pattern-textbox {
-moz-appearance: none !important;
color: white !important;
background-color: #191919 !important;
border: 1px solid black !important;
font: inherit !important;
outline: none !important;}

/*searchbar selected text color*/
#tabswitcher-window #pattern-textbox::selection{color: #00adee !important;background-color: black !important;}

/*main window color*/
#tabswitcher-window{
background-color: #181818 !important;}

/*inner window colors*/
#tabswitcher-window #results-listbox{
background-color: #282828 !important;
color: #a6a6a6 !important;
border-top: 1px solid black !important;}

/*inner window selected row colors*/
#tabswitcher-window .selected{color: #00adee !important; background-color: #1e1e1e !important;}

/*title/url bar background + inner border*/
#tabswitcher-window table {
background-color: #3c3c3c !important;
border: 1px solid black !important;} 

/*title/url bar separator color*/
#tabswitcher-window table th:first-child{border-right: 1px solid black !important;}

/*title/url bar text color+shadow*/
#tabswitcher-window table thead{color: #e7e7e7 !important;text-shadow: 0px 0px 3px rgb(255,255,255) !important;}
```
